//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fr.Brocelia.MazeGen.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MazeTile
    {
        public int id { get; set; }
        public int MazeId { get; set; }
        public int x { get; set; }
        public int y { get; set; }
        public string MapType { get; set; }
    
        public virtual Maze Maze { get; set; }
    }
}
